---
title: "CodeBook"
output: html_document
---

This markdown document describes the variables and units for the tidySet.csv data set. Variables 1 through 66 are average values calculated for each subject and activity. The abbreviation FFT stands for Fast Fourier Transform.

 1. **Mean of Body Acceleration-X:** *Mean of the body's acceleration in the X direction* (g)                                
 2. **Mean of Body Acceleration-Y:** *Mean of the body's acceleration in the Y direction* (g)                                      
 3. **Mean of Body Acceleration-Z:** *Mean of the body's acceleration in the Z direction* (g)                                      
 4. **Mean of Gravity Acceleration-X:** *Mean  acceleration due to gravity in the X direction* (g)                                 
 5. **Mean of Gravity Acceleration-Y:** *Mean  acceleration due to gravity in the Y direction* (g)                                 
 6. **Mean of Gravity Acceleration-Z:** *Mean  acceleration due to gravity in the Z direction* (g)                                 
 7. **Mean of Linear Jerk-X:** *Mean of jerk in the X direction* (g/s)                                           
 8. **Mean of Linear Jerk-Y:** *Mean of jerk in the Y direction* (g/s)                                                         
 9. **Mean of Linear Jerk-Z:** *Mean of jerk in the Z direction* (g/s)                                                         
10. **Mean of Angular Velocity-X:** *Mean of Angular Velocity around the X-axis* (radians/s)
11. **Mean of Angular Velocity-Y:** *Mean of Angular Velocity around the Y-axis* (radians/s)               
12. **Mean of Angular Velocity-Z:** *Mean of Angular Velocity around the Z-axis* (radians/s)                                     
13. **Mean of Angular Jerk-X:** *Mean of jerk around the X axis* (radians/s^3^)                                                       
14. **Mean of Angular Jerk-Y:** *Mean of jerk around the Y axis* (radians/s^3^)                                                      
15. **Mean of Angular Jerk-Z:** *Mean of jerk around the Z axis* (radians/s^3^)                                                      
16. **Mean of Body Acceleration-Magnitude:** *Mean of the magnitude of the body's acceleration* (g)                            
17. **Mean of Gravity Acceleration-Magnitude:** *Mean of the magnitude of acceleration due to gravity* (g)                         
18. **Mean of Linear Jerk-Magnitude:** *Mean of the magnitude linear jerk* (g/s)                                  
19. **Mean of Angular Velocity-Magnitude:** *Mean of the magnitude rotational jerk* (radians/s)                              
20. **Mean of Angular Jerk-Magnitude:** *Mean of the magnitude rotational jerk* (radians/s^3^)                                  
21. **Mean of FFT Body Acceleration-X:** *Mean of the FFT of the body's accleration in the X direction* (g)                                
22. **Mean of FFT Body Acceleration-Y:** *Mean of the FFT of the body's accleration in the Y direction* (g)                                  
23. **Mean of FFT Body Acceleration-Z:** *Mean of the FFT of the body's acceleration in the Z direction* (g)                                  
24. **Mean of FFT Linear Jerk-X:** *Mean of the FFT of jerk in the X direction* (g/s)                                                 
25. **Mean of FFT Linear Jerk-Y:** *Mean of the FFT of jerk in the Y direction* (g/s)                                           
26. **Mean of FFT Linear Jerk-Z:** *Mean of the FFT of jerk in the Z direction* (g/s)                                               
27. **Mean of FFT Angular Velocity-X:** *Mean of the FFT of Angular Velocity in the X direction* (radian/s)                                          
28. **Mean of FFT Angular Velocity-Y:** *Mean of the FFT of Angular Velocity in the Y direction* (radian/s)                                        
29. **Mean of FFT Angular Velocity-Z:** *Mean of the FFT of Angular Velocity in the Z direction* (radian/s)                                       
30. **Mean of FFT Body Acceleration-Magnitude:** *Mean of the FFT of the magnitude of the body's acceleration* (g)                              
31. **Mean of FFT Body x Linear Jerk-Magnitude:** *Mean of the FFT of the magnitude of jerk* (g/s)                         
32. **Mean of FFT Body x Angular Acceleration-Magnitude:** *Mean of the FFT of magnitude of body and angular acceleration* (radians * g/s)              
33. **Mean of FFT Body x Angular Jerk-Magnitude:** *Mean of the FFT of magnitude of body and angular jerk* (radians * g/s^3^)                                    
34. **Standard Deviation of Body Acceleration-X:** *Standard Deviation of acceleration in the X direction* (g)                      
35. **Standard Deviation of Body Acceleration-Y:** *Standard Deviation of acceleration in the Y direction* (g)                         
36. **Standard Deviation of Body Acceleration-Z:** *Standard Deviation of acceleration in the X direction* (g)                         
37. **Standard Deviation of Gravity Acceleration-X:** *Standard Deviation of acceleration due to gravity in the X direction* (g)                   
38. **Standard Deviation of Gravity Acceleration-Y:** *Standard Deviation of acceleration due to gravity in the Y direction* (g)                                      
39. **Standard Deviation of Gravity Acceleration-Z:** *Standard Deviation of acceleration due to gravity in the Z direction* (g)                                      
40. **Standard Deviation of Linear Jerk-X:** *Standard Deviation of jerk in the X direction* (g/s)                                                                  
41. **Standard Deviation of Linear Jerk-Y:** *Standard Deviation of jerk in the Y direction* (g/s)                              
42. **Standard Deviation of Linear Jerk-Z:** *Standard Deviation of jerk in the Z direction* (g/s)                              
43. **Standard Deviation of Angular Velocity-X:** *Standard Deviation of angular velocitys around the X axis* (radians/s)                         
44. **Standard Deviation of Angular Velocity-Y:** *Standard Deviation of angular velocity around the Y axis* (radians/s)                          
45. **Standard Deviation of Angular Velocity-Z:** *Standard Deviation of angular velocity around the Z axis* (radians/s)                          
46. **Standard Deviation of Angular Jerk-X:** *Standard Deviation of jerk around the X axis* (radians/s^3^)                              
47. **Standard Deviation of Angular Jerk-Y:** *Standard Deviation of jerk around the Y axis* (radians/s^3^)                              
48. **Standard Deviation of Angular Jerk-Z:** *Standard Deviation of jerk around the Z axis* (radians/s^3^)                              
49. **Standard Deviation of Body Acceleration-Magnitude:** *Standard Deviation of magnitude of body's acceleration* (g)                                                    
50. **Standard Deviation of Gravity Acceleration-Magnitude:** *Standard Deviation of magnitude of acceleration due to gravity* (g)                                                        
51. **Standard Deviation of Linear Jerk-Magnitude:** *Standard Deviation of magnitude of jerk* (g/s)                                                                 
52. **Standard Deviation of Angular Velocity-Magnitude:** *Standard Deviation of magnitude of angular velocity* (radians/s)                                                            
53. **Standard Deviation of Angular Jerk-Magnitude:** *Standard Deviation of angular jerk* (radians/s^3^)                                                               
54. **Standard Deviation of FFT Body Acceleration-X:** *Standard Deviation of FFT ofacceleration in the X direction* (g)                   
55. **Standard Deviation of FFT Body Acceleration-Y:** *Standard Deviation of FFT ofacceleration in the Y direction* (g)                  
56. **Standard Deviation of FFT Body Acceleration-Z:** *Standard Deviation of FFT ofacceleration in the Z direction* (g)                  
57. **Standard Deviation of FFT Linear Jerk-X:** *Standard Deviation of FFT ofjerk in the X direction* (g)                        
58. **Standard Deviation of FFT Linear Jerk-Y:** *Standard Deviation of FFT ofjerk in the Y direction*  (g)                       
59. **Standard Deviation of FFT Linear Jerk-Z:** *Standard Deviation of FFT ofjerk in the Z direction* (g)                        
60. **Standard Deviation of FFT Angular Velocity-X:** *Standard Deviation of FFT of angular velocity around the X axis* (radians/s)                   
61. **Standard Deviation of FFT Angular Velocity-Y:** *Standard Deviation of FFT of angular velocity around the Y axis* (radians/s)                                      
62. **Standard Deviation of FFT Angular Velocity-Z:** *Standard Deviation of FFT of angular velocity around the Z axis* (radians/s)                                      
63. **Standard Deviation of FFT Body Acceleration-Magnitude:** *Standard Deviation of FFT of magnitude of acceleration* (g)                             
64. **Standard Deviation of FFT Body x Linear Jerk-Magnitude:** *Standard Deviation of FFT of magintude of body jerk* (radians/s^3^)                            
65. **Standard Deviation of FFT Body x Angular Acceleration-Magnitude:** *Standard Deviation of FFT of magintude of body acceleration and angular velocity* (g * radians/s)                            
66. **Standard Deviation of FFT Body x Angular Jerk-Magnitude:** *Standard Deviation of FFT of magintude of body and angular jerk* (g *radians/s^3^)                                    
67. **Activity** *Type of activity conducted*                                                       
68. **Subject** *ID number specifying person conducting activity*     
